spring.application.name=EveryDayHelp
# spring.datasource.url=jdbc:mysql://localhost:3306/everyday_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=root
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:everyday_db;DB_CLOSE_DELAY=-1;MODE=MySQL}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
server.port=8085
