package com.test.EveryDayHelp.Service;

import java.io.File;
import java.io.IOException;
import java.util.List;

import com.test.EveryDayHelp.Entity.*;
import com.test.EveryDayHelp.Repository.*;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class AdminService
{
    private final EmployeeRepository employeeRepository;
    private final AdminRepository adminRepository;
    private final NoticeRepository noticeRepository;
    private final UserRepository userRepository;
    private final ContactRepository contactRepository;
    private final BookingRepository bookingRepository;
    private final FeedbackRepository feedbackRepository;

    // Constructor is auto-generated by @RequiredArgsConstructor

    public void addEmployee(Employee employee, MultipartFile file)
    {
        try
        {
            String projectRoot = System.getProperty("user.dir");
            System.out.println("Project root is " + projectRoot);

            String folderName = "employee_uploads";
            String uploadPath = projectRoot + File.separator + folderName;
            System.out.println("Uploaded path is " + uploadPath);

            File uploadDir = new File(uploadPath);
            if(!uploadDir.exists())
            {
                uploadDir.mkdirs();
                System.out.println("Folder created at " + uploadDir.getAbsolutePath());
            }

            String originalFilename = file.getOriginalFilename();
            System.out.println("File name is " + originalFilename);

            String uniqueFilename = System.currentTimeMillis() + "_" + originalFilename;

            File destinationFile = new File(uploadDir, uniqueFilename);
            file.transferTo(destinationFile);

            System.out.println("Image saved to: " + destinationFile);

            String DB_PATH = folderName + "/" + uniqueFilename;
            employee.setEmployee_pic(DB_PATH);
            employeeRepository.save(employee);
        }
        catch(IOException ie)
        {
            ie.printStackTrace();
        }
    }

    public void addNotice(AdminNotice notice)
    {
        noticeRepository.save(notice);
    }

    public List<UserDetails> allUsers()
    {
        return userRepository.findAll();
    }

    public List<Contacts> allContacts()
    {
        return contactRepository.findAll();
    }

    public List<Employee> allEmployees()
    {
        return employeeRepository.findAll();
    }

    public Admin adminLogin(String email, String password) {
        return adminRepository.findByEmailAndPassword(email, password);
    }

    @Transactional
    public void deleteUser(String email) {
        userRepository.deleteByEmail(email);
    }

    @Transactional
    public void deleteEmployee(String id) {
        employeeRepository.deleteById(id);
    }

    @Transactional
    public void deleteContact(Integer contact_id) {
        contactRepository.deleteById(contact_id);
    }

    public UserDetails editUser(String email) {
        return userRepository.findByEmail(email);
    }

    public void editUserFinal(UserDetails modifiedUser)
    {
        String email = modifiedUser.getEmail();
        UserDetails olduser = userRepository.findByEmail(email);
        olduser.setName(modifiedUser.getName());
        olduser.setPhone(modifiedUser.getPhone());
        olduser.setAddress(modifiedUser.getAddress());
        userRepository.save(olduser);
    }

    public List<AdminNotice> allNotice() {
        return noticeRepository.findAll();
    }

    @Transactional
    public void deleteNotice(Integer noticeId) {
        noticeRepository.deleteById(noticeId);
    }

    public Employee editEmployee(String empId) {
        return employeeRepository.findById(empId).orElse(null);
    }

    @Transactional
    public void editEmployeeFinal(Employee modifiedEmployee, MultipartFile file) {
        Employee oldEmployee = employeeRepository.findById(modifiedEmployee.getEmployee_id()).orElse(null);

        if(oldEmployee != null) {
            // Update all fields
            oldEmployee.setName(modifiedEmployee.getName());
            oldEmployee.setPhone(modifiedEmployee.getPhone());
            oldEmployee.setQualification(modifiedEmployee.getQualification());
            oldEmployee.setExperience(modifiedEmployee.getExperience());
            oldEmployee.setGender(modifiedEmployee.getGender());
            oldEmployee.setEmployee_type(modifiedEmployee.getEmployee_type());
            oldEmployee.setService_type(modifiedEmployee.getService_type());
            oldEmployee.setCharges(modifiedEmployee.getCharges());
            oldEmployee.setDescription(modifiedEmployee.getDescription());

            // Handle file upload if a new file is provided
            if (file != null && !file.isEmpty()) {
                try {
                    String projectRoot = System.getProperty("user.dir");
                    String folderName = "employee_uploads";
                    String uploadPath = projectRoot + File.separator + folderName;

                    File uploadDir = new File(uploadPath);
                    if (!uploadDir.exists()) {
                        uploadDir.mkdirs();
                    }

                    String originalFilename = file.getOriginalFilename();
                    String uniqueFilename = System.currentTimeMillis() + "_" + originalFilename;
                    File destinationFile = new File(uploadDir, uniqueFilename);
                    file.transferTo(destinationFile);

                    String DB_PATH = folderName + "/" + uniqueFilename;
                    oldEmployee.setEmployee_pic(DB_PATH);
                } catch (IOException ie) {
                    ie.printStackTrace();
                }
            }

            employeeRepository.save(oldEmployee);
        }
    }

    // Booking Management
    public List<Booking> getAllBookings() {
        return bookingRepository.findAll();
    }

    @Transactional
    public void approveBooking(Integer id, String timeSlot, String adminMessage) {
        Booking booking = bookingRepository.findById(id).orElse(null);
        if (booking != null) {
            booking.setStatus("Activated");
            booking.setTimeSlot(timeSlot);
            if (adminMessage != null && !adminMessage.isEmpty()) {
                booking.setAdminMessage(adminMessage);
            } else {
                booking.setAdminMessage("Your booking has been approved! Time slot: " + timeSlot);
            }
            bookingRepository.save(booking);
        }
    }

    @Transactional
    public void rejectBooking(Integer id, String adminMessage) {
        Booking booking = bookingRepository.findById(id).orElse(null);
        if (booking != null) {
            booking.setStatus("Rejected");
            if (adminMessage != null && !adminMessage.isEmpty()) {
                booking.setAdminMessage(adminMessage);
            } else {
                booking.setAdminMessage("Sorry, your booking has been rejected.");
            }
            bookingRepository.save(booking);
        }
    }

    // Feedback Management
    public List<Feedback> getAllFeedbacks() {
        return feedbackRepository.findAll();
    }
}